packages:
  - packages/*
  - samples/*
catalog:
  "@alloy-js/core": "^0.5.0"
  "@alloy-js/typescript": "^0.5.0"
  "typescript": "^5.8.2"
  "@typespec/compiler": "^0.65.3"
  "@typespec/emitter-framework": "^0.1.0"
  "vitest": "^2.0.3"
  "zod": "^3.24.2"
